name: Generate

on:
  push:
  schedule:
    - cron: '0 4 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24.0'

      - name: Pull vendors
        run: make pull-vendors

      - name: Build
        run: make build

      - name: Generate
        run: make gen-all

      - name: Slice routes
        run: make slice-routes

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
